version: '3.1'

services:
  db:
    build: .
    container_name: devtraining-db
    restart: always
    ports:
      - '9876:9876'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtraining